### PR TITLE
Add MIT license

### PR DESCRIPTION
**Pull request by cugu**
See https://github.com/kaitai-io/kaitai_struct/issues/474

### CODE REVIEW

**Comment by cherue** [comment]
This requires consent from @generalmimon and @sealmove. Do you approve of this license?

**Comment by generalmimon** [comment]
> Do you approve of this license?

I do 👍. I just wasn't sure if this issue is still relevant, @GreyCat mentioned in https://github.com/kaitai-io/kaitai_struct/issues/474#issuecomment-599046984 that he'd rather strip `ci_targets` repo from all copyrightable content, marking it just a derivative of the [compiler](https://github.com/kaitai-io/kaitai_struct_compiler) and [tests](https://github.com/kaitai-io/kaitai_struct_tests) (anyone can grab the `master` compiler and tests and generate the exact same content stored in `compiled/` folder currently).

But until that comes reality (there are still a bunch of `prepare-*` scripts that are vital for making the tests work), I see no problem merging this if @sealmove allows. We can make the proposed change at any other time.

@cugu, @cherue Thank you both for taking care about the licensing, it's an essential prerequisite to be able to call this whole stuff "open-source" and it unfortunately doesn't get as much attention as it should.

**Comment by sealmove** [comment]
I approve.

**Comment by cherue** [comment]
@GreyCat this can be merged now.

**Comment by GreyCat** [comment]
Sure, thanks!

**Pull request merged**
